CONDA_DEFAULT_ENV=fenicsproject
CONDA_EXE=/Users/jackh/opt/anaconda3/bin/conda
CONDA_PREFIX=/Users/jackh/opt/anaconda3/envs/fenicsproject
CONDA_PREFIX_1=/Users/jackh/opt/anaconda3
CONDA_PROMPT_MODIFIER='(fenicsproject) '
CONDA_PYTHON_EXE=/Users/jackh/opt/anaconda3/bin/python
CONDA_SHLVL=2
HOME=/Users/jackh
HOMEBREW_CELLAR=/opt/homebrew/Cellar
HOMEBREW_PREFIX=/opt/homebrew
HOMEBREW_REPOSITORY=/opt/homebrew
HOMEBREW_SHELLENV_PREFIX=/opt/homebrew
INFOPATH=/opt/homebrew/share/info:
LANG=en_AU.UTF-8
LOGNAME=jackh
MANPATH=/opt/homebrew/share/man::
OLDPWD=/Users/jackh/Documents/fem_fenics
PATH=/Users/jackh/opt/anaconda3/envs/fenicsproject/bin:/Users/jackh/opt/anaconda3/condabin:/opt/homebrew/bin:/opt/homebrew/sbin:/Library/Frameworks/Python.framework/Versions/3.9/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
PWD=/Users/jackh/Documents/fem_fenics/katana_export
SHELL=/bin/zsh
SHLVL=1
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.6QNLzU3lHH/Listeners
TERM=xterm-256color
TERM_PROGRAM=Apple_Terminal
TERM_PROGRAM_VERSION=440
TERM_SESSION_ID=D8522FDB-98CF-437F-A698-0EDBB49BCC88
TMPDIR=/var/folders/9v/f6c01sn97rb6v_y68jr4gcn80000gn/T/
USER=jackh
XPC_FLAGS=0x0
XPC_SERVICE_NAME=0
_CE_CONDA=''
_CE_M=''
__CFBundleIdentifier=com.apple.Terminal
